classdef AIHelper < handle
    properties
        ApiKey
        ModelName = "gemini-2.5-flash"
    end

    methods
        function obj = AIHelper(apiKey)
            % Constructor: store API key
            obj.ApiKey = apiKey;
        end

        %% Method: Ask ECE Tutor Question
        function text = askTutorQuestion(obj, userInput)
            % Sends a student question to Gemini and returns the AI's response
            prompt = sprintf([ ...
                'You are an expert Electrical and Computer Engineering tutor.\n' ...
                'Respond clearly, beginner-friendly, avoid LaTeX or advanced symbols.\n' ...
                'Question: "%s"\n' ...
                ], userInput);

            api_url = ['https://generativelanguage.googleapis.com/v1beta/models/', ...
                        obj.ModelName, ':generateContent?key=', obj.ApiKey];

            requestBody = struct( ...
                "contents", { ...
                    struct( ...
                        "role", "user", ...
                        "parts", { struct("text", prompt) } ...
                    ) ...
                } ...
            );

            options = weboptions('RequestMethod','post','MediaType','application/json','Timeout',30);

            try
                response = webwrite(api_url, requestBody, options);
                if isfield(response, 'candidates') && ~isempty(response.candidates)
                    text = response.candidates(1).content.parts.text;
                else
                    text = "No response received from the AI.";
                end
            catch ME
                text = "Request failed: " + ME.message;
            end
        end

        %% Method: Generate Circuit Grid
        function jsonStruct = generateCircuitGrid(obj, userText)
            % Sends a circuit layout request to Gemini and returns JSON struct
            instruction = sprintf([ ...
                'You are a circuit layout generator. Generate ONLY valid JSON.\n\n' ...
                '### GRID RULES\n' ...
                '- Grid is 20x20.\n' ...
                '- Coordinates are [x, y] with (0,0) at top-left.\n' ...
                '- Components occupy a single cell (use "coord").\n' ...
                '- Wires are elements with "coords" arrays of adjacent cells.\n' ...
                '- Rotations (if present) must be one of: 0, 90, 180, 270.\n\n' ...
                '### JSON FORMAT (EXACT)\n' ...
                '{\n' ...
                '  "grid_size": [20, 20],\n' ...
                '  "elements": [\n' ...
                '    { "type": "battery", "coord": [x, y], "rotation": 0 },\n' ...
                '    { "type": "wire", "coords": [[x1,y1],[x2,y2],...] }\n' ...
                '  ]\n' ...
                '}\n\n' ...
                '### RULES\n' ...
                '- Return JSON only. No explanation, no commentary, no backticks.\n' ...
                '- All coordinates must be inside the grid (0..19 for x and y).\n' ...
                '- Wires must be continuous lists of adjacent cells.\n\n' ...
                '### USER REQUEST:\n' ...
                '%s\n\n' ...
                'Return ONLY valid JSON as the model output.\n' ...
                'Use 1-based coordinates instead of 0-based.' ...
                ], userText);

            api_url = ['https://generativelanguage.googleapis.com/v1beta/models/', ...
                        obj.ModelName, ':generateContent?key=', obj.ApiKey];

            body = struct('contents', { struct('parts', { struct('text', instruction) }) });

            options = weboptions('RequestMethod', 'post', 'MediaType', 'application/json', 'Timeout', 60);

            try
                response = webwrite(api_url, body, options);

                % Handle cell array or struct array response
                cand = response.candidates;
                if iscell(cand)
                    rawText = cand{1}.content.parts{1}.text;
                else
                    rawText = cand(1).content.parts(1).text;
                end

                jsonStruct = jsondecode(rawText);
            catch ME
                error('AIHelper generateCircuitGrid failed: %s', ME.message);
            end
        end

        %% Optional: Generate Quiz Questions
        function questions = generateQuizQuestions(obj, numQuestions, difficulty)
            % Asks Gemini to generate a JSON array of quiz questions
            prompt = sprintf([ ...
                'Generate %d Electrical Engineering quiz questions.\n' ...
                'Difficulty: %s\n' ...
                'Return JSON array of objects: { "question": "...", "answer": "...", "choices": ["..."] }\n' ...
                'Do not include explanations, only question, answer, and choices.'], ...
                numQuestions, difficulty);

            api_url = ['https://generativelanguage.googleapis.com/v1beta/models/', ...
                        obj.ModelName, ':generateContent?key=', obj.ApiKey];

            requestBody = struct( ...
                "contents", { struct("role", "user", "parts", { struct("text", prompt) }) } ...
            );

            options = weboptions('RequestMethod','post','MediaType','application/json','Timeout',60);

            try
                response = webwrite(api_url, requestBody, options);
                rawText = response.candidates(1).content.parts.text;
                questions = jsondecode(rawText);
            catch ME
                error('AIHelper generateQuizQuestions failed: %s', ME.message);
            end
        end
    end
end
